name: selenium
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          
      - name: 'Install requirements'
        run: pip install -r requirements.txt
  
      - name: 'Working'
        run: python sign.py
        env:
             xiaoaishe_username: ${{ secrets.XIAOAISHE_USERNAME }}
             xiaoaishe_password: ${{ secrets.XIAOAISHE_PASSWORD }}
             maozhua_username: ${{ secrets.MAOZHUA_USERNAME }}
             maozhua_password: ${{ secrets.MAOZHUA_PASSWORD }}
