name: selenium
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '03 16 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        
      - name: 'Install requirements'
        run: pip install -r requirements.txt
  
      - name: 'Working'
        run: python sign.py
        env:
             xiaoaishe_username: ${{ secrets.XIAOAISHE_USERNAME }}
             xiaoaishe_password: ${{ secrets.XIAOAISHE_PASSWORD }}
             maozhua_username: ${{ secrets.MAOZHUA_USERNAME }}
             maozhua_password: ${{ secrets.MAOZHUA_PASSWORD }}
