name: selenium
on: 
  #push:
  workflow_dispatch:
  schedule:
    - cron:  '02 00 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        
      - uses: nanasess/setup-chromedriver@v1
        #with:
          # Optional: do not specify to match Chrome's version
          #chromedriver-version: '101.0.4951.41'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          
      - name: 'Install requirements'
        run: pip install -r requirements.txt
  
      - name: 'Working'
        run: python sign.py
        env:
             xiaoaishe_username: ${{ secrets.XIAOAISHE_USERNAME }}
             xiaoaishe_password: ${{ secrets.XIAOAISHE_PASSWORD }}
             maozhua_username: ${{ secrets.MAOZHUA_USERNAME }}
             maozhua_password: ${{ secrets.MAOZHUA_PASSWORD }}
             sdai_username: ${{ secrets.SDAI_USERNAME }}
             sdai_password: ${{ secrets.SDAI_PASSWORD }}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
